package life.majiang.community.community.mapper;

//import java.util.List;
//import life.majiang.community.model.Question;
//import life.majiang.community.model.QuestionExample;
//import org.apache.ibatis.annotations.Param;
//import org.apache.ibatis.session.RowBounds;


import life.majiang.community.community.model.Question;
import org.apache.ibatis.annotations.Insert;

public interface QuestionMapper {
    @Insert("insert into (title,description,gmt_create,gmt_modified,creator,tag) " +
            "values(#{title},#{description},#{gmtCreate},#{gmtModified},#{creator},#{tag})")
     void create(Question question);

}
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    long countByExample(QuestionExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    int deleteByExample(QuestionExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    int deleteByPrimaryKey(Long id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    int insert(Question record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    int insertSelective(Question record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    List<Question> selectByExampleWithBLOBsWithRowbounds(QuestionExample example, RowBounds rowBounds);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    List<Question> selectByExampleWithBLOBs(QuestionExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    List<Question> selectByExampleWithRowbounds(QuestionExample example, RowBounds rowBounds);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    List<Question> selectByExample(QuestionExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    Question selectByPrimaryKey(Long id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    int updateByExampleSelective(@Param("record") Question record, @Param("example") QuestionExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    int updateByExampleWithBLOBs(@Param("record") Question record, @Param("example") QuestionExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    int updateByExample(@Param("record") Question record, @Param("example") QuestionExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    int updateByPrimaryKeySelective(Question record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    int updateByPrimaryKeyWithBLOBs(Question record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table QUESTION
//     *
//     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
//     */
//    int updateByPrimaryKey(Question record);
//}